services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AWS_REGION=${AWS_REGION}
      - DEVICE_TABLE_NAME=machine_table
      - DATA_TABLE_NAME=machine_data_table
      - USER_TABLE_NAME=users
      - IOT_POLICY_NAME=iot_p
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./:/app
    restart: unless-stopped
    command: air
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
