version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AWS_REGION=us-east-1
      - DEVICE_TABLE_NAME=devices
      - DATA_TABLE_NAME=machine_data
      - USER_TABLE_NAME=users
      - IOT_POLICY_NAME=DefaultIoTPolicy
      # AWS credentials should be set in environment or mounted from a secure source
      # - AWS_ACCESS_KEY_ID=your_access_key
      # - AWS_SECRET_ACCESS_KEY=your_secret_key
    volumes:
      - ./:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

